//------------------------------------------------------------------------------
// <auto-generated>
using System;
using System.Collections.Generic;
namespace Incorrect.Core.Model
{
    public  class ExamTestEx_Info
    {
        public int ExamID { get; set; }
        public Nullable<int> HasBindingline { get; set; }
        public Nullable<int> HasConfidentialMark { get; set; }
        public Nullable<int> HasStuInputColumn { get; set; }
        public Nullable<int> HasInfoColumn { get; set; }
        public Nullable<int> HasTranscribeColumn { get; set; }
        public Nullable<int> HasAttentionColumn { get; set; }
        public Nullable<int> HasBigQAttentionColumn { get; set; }
        public Nullable<int> HasBigQScoreColumn { get; set; }
        public Nullable<int> HasPaper1 { get; set; }
        public Nullable<int> HasPaper2 { get; set; }
        public Nullable<int> HasPaper3 { get; set; }
        public string PagerTitle1 { get; set; }
        public string PagerTitle2 { get; set; }
        public string PagerTitle3 { get; set; }
        public Nullable<int> HasChoiceColumn { get; set; }
        public Nullable<int> HasChoiceScore { get; set; }
        public string ChoiceTitle { get; set; }
        public string ChoiceDesc { get; set; }
        public Nullable<int> HasFillColumn { get; set; }
        public Nullable<int> HasFillScore { get; set; }
        public string FillTitle { get; set; }
        public string FillDesc { get; set; }
        public string StuInputColumn { get; set; }
    }
}
